# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\nconnection\"\\\n\x11\x43onnectionRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x0e\n\x06meters\x18\x04 \x01(\x05\"A\n\x12\x43onnectionResponse\x12+\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x16.connection.Connection\"X\n\nConnection\x12&\n\x08location\x18\x01 \x01(\x0b\x32\x14.connection.Location\x12\"\n\x06person\x18\x02 \x01(\x0b\x32\x12.connection.Person\"e\n\x08Location\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\"Q\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t2d\n\x11\x43onnectionService\x12O\n\x0c\x46indContacts\x12\x1d.connection.ConnectionRequest\x1a\x1e.connection.ConnectionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTIONREQUEST._serialized_start=32
  _CONNECTIONREQUEST._serialized_end=124
  _CONNECTIONRESPONSE._serialized_start=126
  _CONNECTIONRESPONSE._serialized_end=191
  _CONNECTION._serialized_start=193
  _CONNECTION._serialized_end=281
  _LOCATION._serialized_start=283
  _LOCATION._serialized_end=384
  _PERSON._serialized_start=386
  _PERSON._serialized_end=467
  _CONNECTIONSERVICE._serialized_start=469
  _CONNECTIONSERVICE._serialized_end=569
# @@protoc_insertion_point(module_scope)
