openapi: "3.0.0"
info:
  title: Persons API
  version: "1.0.0"
  description: API for managing persons 
  contact:
    email: info@personsapi.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "http://localhost:5000"
    description: Development server

paths:
  /persons:
    post:
      summary: Create a new Person.
      requestBody:
        description: Person object that needs to be added to the system.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        "200":
          description: Person created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
    get:
      summary: Retrieve all Persons.
      responses:
        "200":
          description: List of Persons retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

  /persons/{person_id}:
    get:
      summary: Retrieve a Person by ID.
      parameters:
        - name: person_id
          in: path
          description: Unique ID for a given Person.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Person retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the Person.
        first_name:
          type: string
          description: First name of the Person.
        last_name:
          type: string
          description: Last name of the Person.
        company_name:
          type: string
          description: Company name of the Person.
      required:
        - first_name
        - last_name
        - company_name
